version: '3.9'
services:
  monitoring-redis:
    image: redis:6.2.4-alpine
    ports:
      - 6379:6379
    volumes:
      - ./monitoring-db:/data
    networks:
      monitoring-network:
        ipv4_address: 10.10.0.10
  node:
    image: node:16.13.1-alpine
    ports:
      - 4000:3000
    build: .
    links:
      - "monitoring-redis:db"
    networks:
      monitoring-network:
        ipv4_address: 10.10.0.11
    depends_on:
      - monitoring-redis

networks:
  monitoring-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.10.0.1
